export const notifier = {
	NEW_MESSAGES: 'NEW_MESSAGES',
	CLOSE_MESSAGE: 'CLOSE_MESSAGE',
	SHOW_MESSAGE: 'SHOW_MESSAGE',
	COUNT_UP: 'COUNT_UP'
}

export const selectbox = {
	SET: 'SET_SELECTBOX',
	ADD: 'ADD_SELECTBOX',

	// local mutations
	OPEN: 'OPEN_SELECTBOX',
	CLOSE: 'CLOSE_SELECTBOX',

	TEXT: 'SET_SELECTBOX_TEXT',
	VALUE: 'SET_SELECTBOX_VALUE',
	FIRST_RENDERING: 'SET_SELECTBOX_FIRST_RENDERING'
}

export const liqpay = {
	DATA: 'SET_LIQPAY_DATA',
	SIGNATURE: 'SET_LIQPAY_SIGNATURE'
}


export const counter = {
	INCR: 'INCREMENT_COUNTER',
	DECR: 'DECREMENT_COUNTER',
	VALUE: 'SET_COUNTER_VALUE'
}
